In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-5.1223e-09, grad_fn=<MeanBackward0>)

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-0.7908, -0.2897,  0.5945],
        [ 0.2872,  0.1478,  0.2363],
        [ 0.8848, -0.5880,  1.7398],
        [ 0.9967,  1.3198,  0.6156],
        [-1.3955, -0.3842, -0.5728]], requires_grad=True)

In [5]:
dense(torch.rand(2, 5))

tensor([[0.0000, 0.4333, 1.6882],
        [0.0000, 0.2149, 1.1064]], grad_fn=<ReluBackward0>)

In [6]:
net = nn.Sequential(
    MyLinear(64, 8),
    MyLinear(8, 1)
)
net(torch.rand(2, 64))

tensor([[0.0000],
        [4.9473]], grad_fn=<ReluBackward0>)